// Angular_React_Vue/Day7/Practice/Practice3/Source/child-to-parent/src/components/Profile.vue
<script>
export default {
    data() {
        return {
            name: ''
        }
    },
    methods: {
        displayname(name) {
            this.$emit('display', this.name)
        }
    }
}
</script>

<template>
    <label class="text-xl ">Name : </label><br>
    <input type="text"
        class="border border-black rounded-xl my-2 form-control pl-2 focus:border-green-900 focus:outline-none focus:border-2"
        name="name" id="name" v-model="name" @input="displayname(name)" placeholder="Enter Name Here... ">
</template>

// Angular_React_Vue/Day7/Practice/Practice2/Source/child-to-parent/src/app/profile/profile.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  @Output() display = new EventEmitter<string>();
  constructor() { }
  displayname(name: string) {
    this.display.emit(name);
  }
  ngOnInit(): void {
  }

}
<label class="text-xl ">Name : </label><br>
<input type="text" class="border border-black rounded-xl my-2 form-control pl-2 focus:border-green-900 focus:outline-none focus:border-2" 
name="name" id="name" #name (input)="displayname(name.value)" placeholder="Enter Name Here... ">
