// Angular_React_Vue/Day6/Assignments/Assignment1/Source/productdetails/src/app/product/product.component.ts
import { Component, OnInit } from '@angular/core';
import Product from './productInterface';
@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent implements OnInit {

  ProductName:string='';
  Price:string='';
  Qty:string='';
  Products:Product[]=[];
  constructor() { }
  AddProduct(){
    this.Products.push({
      Name:this.ProductName,
      Price:parseFloat(this.Price),
      Qty:parseInt(this.Qty),
      Gross:(parseFloat(this.Price)*parseInt(this.Qty)),
      Discount:((parseFloat(this.Price)*parseInt(this.Qty))*0.05).toFixed(2),
      PayableAmount:((parseFloat(this.Price)*parseInt(this.Qty))-((parseFloat(this.Price)*parseInt(this.Qty))*0.05)).toFixed(2)})
  }
  ngOnInit(): void {
  }

}

<div class="border border-black mx-auto w-fit p-5">
    <label>Product Name : </label><br>
<input type="text" class="border border-black form-control px-1" name="Name" id="name" [(ngModel)]="ProductName"><br><br>
<label>Product Price : </label><br>
<input type="number" class="border border-black form-control px-1" name="Name" id="price" [(ngModel)]="Price"><br><br>
<label>Product Qty : </label><br>
<input type="number" class="border border-black form-control px-1" name="Name" id="qty" [(ngModel)]="Qty"><br><br>
<button class="border border-black px-2 py-1 rounded-xl hover:bg-gray-200" (click)="AddProduct()">Add Product</button>
</div>
<app-product-list [productList]="Products"></app-product-list>

// Angular_React_Vue/Day6/Assignments/Assignment3/Source/productdetails/src/components/Product.js
import {useState} from 'react'
import ProductList from './Productlist';
export default function Product(){
    const [product, setproduct] = useState({});
    const [Products, setProducts] = useState([]);
    return(
        <>
        <div className='border p-5 mb-5 w-fit mx-auto'>
            <label for='productname'>ProductName : </label><br></br>
            <input type='text' className='border border-black px-1' id='productname' onChange={e=>setproduct(p=>({...p,ProductName:e.target.value}))}></input><br></br><br></br>
            <label for='Price'>Price : </label><br></br>
            <input type='number' className='border border-black px-1' id='Price' onChange={e=>setproduct(p=>({...p,Price:e.target.value}))}></input><br></br><br></br>
            <label for='Qty'>Qty : </label><br></br>
            <input type='number' className='border border-black px-1' id='Qty' onChange={e=>setproduct(p=>({...p,Qty:e.target.value}))}></input><br></br><br></br>
            <button className='border border-black rounded-xl px-2 py-1 hover:bg-gray-200 mb-3' onClick={
                e=>{
                    e.preventDefault();
                    setProducts([...Products,{ProductName:product.ProductName,Price:product.Price,Qty:product.Qty,Gross:(product.Price * product.Qty),
                        Discount:((product.Price * product.Qty)*0.05).toFixed(2),PayableAmount:((product.Price * product.Qty)-((product.Price * product.Qty)*0.05)).toFixed(2)}])
                }
            }>Add Product</button>
        </div>
        {Products.length !==0 &&
        <ProductList products={Products}></ProductList>}
        </>
    )
}
