// Angular_React_Vue/Day6/Assignments/Assignment1/Source/productdetails/src/app/product-list/product-list.component.ts
import { Component, OnInit,Input } from '@angular/core';
import Product from '../product/productInterface';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
  @Input() productList!:Product[];

  constructor() { }

  ngOnInit(): void {
  }

}

<table *ngIf="productList.length !==0" class="border border-black border-collapse mx-auto">
    <caption>Product List : </caption>
<thead class="bg-gray-200">
<th class="border border-black p-2">Product Name</th>
<th class="border border-black p-2">price</th>
<th class="border border-black p-2">Qty</th>
<th class="border border-black p-2">Gross Amount</th>
<th class="border border-black p-2">Discount</th>
<th class="border border-black p-2">Payable Amount</th>
</thead>
<tbody>
    <tr class="even:bg-gray-200" *ngFor="let item of productList">
        <td class="border border-black p-1">{{item.Name}}</td>
        <td class="border border-black p-1">{{item.Price}}</td>
        <td class="border border-black p-1">{{item.Qty}}</td>
        <td class="border border-black p-1">{{item.Gross}}</td>
        <td class="border border-black p-1">{{item.Discount}}</td>
        <td class="border border-black p-1">{{item.PayableAmount}}</td>
    </tr>
</tbody>
</table>

// Angular_React_Vue/Day6/Assignments/Assignment3/Source/productdetails/src/components/Productlist.js
export default function ProductList(props){
    return(
        <>
        <table className="border border-black border-collapse mx-auto">
            <thead className="bg-gray-200">
                <th className="border border-black">ProductName</th>
                <th className="border border-black">Price</th>
                <th className="border border-black">Qty</th>
                <th className="border border-black">Gross Amount</th>
                <th className="border border-black">Discount</th>
                <th className="border border-black">PayableAmount</th>
            </thead>
        {props.products.map(item=>
            <tr className="odd:bg-gray-200" key={item.ProductName}>
                <td className="border border-black p-1">{item.ProductName}</td>
                <td className="border border-black p-1">{item.Price}</td>
                <td className="border border-black p-1">{item.Qty}</td>
                <td className="border border-black p-1">{item.Gross}</td>
                <td className="border border-black p-1">{item.Discount}</td>
                <td className="border border-black p-1">{item.PayableAmount}</td>
            </tr>
            )}
        </table>
        </>
    )
}
