// Angular_React_Vue/Day4/Assignments/Assignment1/Source/EmployeeDetails/src/components/Employee.vue
<script>
import '../style.css'
export default {
    data() {
        return {
            eid: '',
            EName: '',
            Address: '',
            Gender: '',
            DOJ: '',
            Emps: [],
            hobbies: [],
            FMonth: '',
            Fname: '',
            filteredbyMongth: [],
            filterbyname: []
        }
    },
    methods: {
        SaveEmp() {
            this.Emps.push({ ID: this.eid, Name: this.EName, Address: this.Address, Gender: this.Gender, DOJ: this.DOJ, Hobbies: this.hobbies.join(',') });
        },
        getBymonth() {
            this.filteredbyMongth = this.Emps.filter(value => value.DOJ.split('-')[1] == this.FMonth)
        },
        getByName() {
            this.filterbyname = this.Emps.filter(value => value.Name.match(this.Fname));
        }
    }
}
</script>

<template>
    <div class="mx-5">
        <fieldset action="" class="border p-5">
            <legend>Employee</legend>
            <label for="eid">Employee ID : </label>
            <input type="number" class="border form-control" name="EmpID" id="eid" v-model=eid><br><br>
            <label for="name">Eployee's Name : </label>
            <input type="text" class="border form-control" name="EName" id="name" v-model=EName><br><br>
            <label for="Address">Address : </label>
            <input type="text" class="border form-control" name="Address" id="Address" v-model=Address><br><br>
            <label for="Gender">Select Gender : </label>
            <span class="space-x-4">
                <span class="space-x-1">
                    <input type="radio" class="form-check-input" name="gender" id="male" v-model=Gender
                        value="Male"><label for="male">Male</label>
                </span>
                <span class="space-x-1">
                    <input type="radio" class="form-check-input" name="gender" id="female" v-model=Gender
                        value="Female"><label for="female">Female</label>
                </span>
            </span>
            <br><br>
            <label for="DOJ">DOJ : </label>
            <input type="date" class="border form-control" name="DOJ" id="DOJ" v-model="DOJ"><br><br>
            <label for="hobbies">Hobbies : </label>
            <span class="space-x-4">
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Swimming" v-model="hobbies">
                    <label>Swimming</label>
                </span>
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Reading" v-model="hobbies">
                    <label>Reading</label>
                </span>
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Playing" v-model="hobbies">
                    <label>Playing</label>
                </span>
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Others" v-model="hobbies">
                    <label>Others</label>
                </span>
            </span>
            <br><br>
            <button class="border rounded-xl px-5 py-1 hover:bg-blue-400 hover:text-white"
                @click.stop.prevent="SaveEmp()">save</button>
        </fieldset><br><br><br>

        <div class='mb-3 flex justify-between'>
            <span class="space-x-2">
                <label for="MonthFilter">By Month : </label>
                <input type="number" class="border form-control" name="MonthFilter" id="MonthFilter" v-model="FMonth"
                    @keyup="getBymonth">
            </span>
            <span class="space-x-2">
                <label for="SortByName">By Name : </label>
                <input type="text" class="border form-control" name="SortByName" id="SortByName" v-model="Fname"
                    @keyup="getByName">
            </span>

        </div><br>

        <table class="border-collapse border text-center  table-auto border-zinc-900 w-full ">
            <caption>Employees Detail :</caption>
            <tr class="bg-neutral-400">
                <th class="border border-zinc-900 p-2">ID</th>
                <th class="border border-zinc-900 p-2">Name</th>
                <th class="border border-zinc-900 p-2">Address</th>
                <th class="border border-zinc-900 p-2">Gender</th>
                <th class="border border-zinc-900 p-2">DOJ</th>
                <th class="border border-zinc-900 p-2">Hobbies</th>
            </tr>
            <tr v-if="Emps.length === 0">
                <td class="border text-3xl" colspan="6"> There is no data </td>
            </tr>
            <tr class="odd:bg-neutral-400" v-else-if="filteredbyMongth.length !== 0" v-for="i of filteredbyMongth">
                <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
            </tr>
            <tr class="odd:bg-neutral-400" v-else-if="filterbyname.length !== 0" v-for="i of filterbyname">
                <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
            </tr>
            <tr class="odd:bg-neutral-400" v-else v-for=" i of Emps">
                <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
            </tr>
        </table>
    </div>
</template>

// Angular_React_Vue/Day5/Assignments/Assignment1/Source/employeedetails/src/components/Employee.js
import { useState } from "react";
import './Employee.css'
import 'tw-elements';
export function Display(props) {
    if (props.emps.length === 0) {
        return (
            <tr className="text-4xl">
                <td className="p-2" colSpan={6}>There is no data to show</td>
            </tr>
        )
    }
    else if (props.Name) {
        return (
            <>
                {props.emps.filter(item => item.Name.match(props.Name)).map(item =>
                    <tr className="even:bg-neutral-400" key={item.Id}>
                        <td className="border border-zinc-900 p-1">{item.Id}</td>
                        <td className="border border-zinc-900 p-1">{item.Name}</td>
                        <td className="border border-zinc-900 p-1">{item.Address}</td>
                        <td className="border border-zinc-900 p-1">{item.Gender}</td>
                        <td className="border border-zinc-900 p-1">{item.DOJ}</td>
                        <td className="border border-zinc-900 p-1">{item.hobbies.toString()}</td>
                    </tr>
                )}
            </>
        )
    }
    else if (props.month) {
        return (
            <>
                {props.emps.filter(item => parseInt(item.DOJ.split('-')[1]) === parseInt(props.month)).map(item =>
                    <tr className="even:bg-neutral-400" key={item.Id}>
                        <td className="border border-zinc-900 p-1">{item.Id}</td>
                        <td className="border border-zinc-900 p-1">{item.Name}</td>
                        <td className="border border-zinc-900 p-1">{item.Address}</td>
                        <td className="border border-zinc-900 p-1">{item.Gender}</td>
                        <td className="border border-zinc-900 p-1">{item.DOJ}</td>
                        <td className="border border-zinc-900 p-1">{item.hobbies.toString()}</td>
                    </tr>
                )}
            </>
        )
    }
    else {
        return (
            <>
                {props.emps.map(item =>
                    <tr className="even:bg-neutral-400" key={item.Id}>
                        <td className="border border-zinc-900 p-1">{item.Id}</td>
                        <td className="border border-zinc-900 p-1">{item.Name}</td>
                        <td className="border border-zinc-900 p-1">{item.Address}</td>
                        <td className="border border-zinc-900 p-1">{item.Gender}</td>
                        <td className="border border-zinc-900 p-1">{item.DOJ}</td>
                        <td className="border border-zinc-900 p-1">{item.hobbies.toString()}</td>
                    </tr>
                )
                }
            </>
        )
    }


}
export function Employee() {
    const [employee, setEmployee] = useState({})
    const [emps, setEmps] = useState([])
    const [hobbies, sethobbies] = useState({ hobby: [] });
    const [Fmonth, setFmonth] = useState('');
    const [FName, setFName] = useState('')

    const handleChange = (e) => {
        const { value, checked } = e.target;
        const { hobby } = hobbies;

        if (checked) {
            sethobbies({ hobby: [...hobby, value] });
        }
        else {
            sethobbies({ hobby: hobby.filter((e) => e !== value) })
        }
    };


    return (
        <div className='ml-5 mr-5'>
            <fieldset action="" className="border p-5">
                <legend>Employee</legend>
                <label >Employee ID : </label>
                <input className="form-control border" type="number" name="EmpID" id="eid" onChange={e => setEmployee(f => ({ ...f, Id: e.target.value }))} /><br></br><br></br>
                <label >Eployee's Name : </label>
                <input className="form-control border" type="text" name="EName" id="name" onChange={e => setEmployee(f => ({ ...f, Name: e.target.value }))} /><br></br><br></br>
                <label >Address : </label>
                <input className="form-control border" type="text" name="Address" id="Address" onChange={e => setEmployee(f => ({ ...f, Address: e.target.value }))} /><br></br><br></br>
                <label >Select Gender : </label>
                <span className='space-x-4'>
                    <span  className='space-x-1'>

                        <input className="form-control border" type="radio" name="gender" id="male" onClick={e => setEmployee(f => ({ ...f, Gender: e.target.value }))} value="Male" />
                        <label >Male</label>
                    </span>
                    <span className='space-x-1'>

                        <input className="form-control border" type="radio" name="gender" id="female" onClick={e => setEmployee(f => ({ ...f, Gender: e.target.value }))} value="Female" />
                        <label  >Female</label>
                    </span>

                </span>

                <br></br><br></br>
                <label >DOJ : </label>
                <input className="form-control border" type="date" name="DOJ" id="DOJ" onChange={e => setEmployee(f => ({ ...f, DOJ: e.target.value }))} /><br></br><br></br>
                <label >Hobbies : </label>
                <span className='space-x-4'>
                    <span className='space-x-1'>
                        <input className="form-check-input border" type="checkbox" name="hobbies" onChange={handleChange} value="Swimming" />
                        <label>Swimming</label>
                    </span>
                    <span className='space-x-1'>
                        <input className="form-check-input border" type="checkbox" name="hobbies" onChange={handleChange} value="Reading" />
                        <label>Reading</label>
                    </span>
                    <span className='space-x-1'>
                        <input className="form-check-input border" type="checkbox" name="hobbies" onChange={handleChange} value="Playing" />
                        <label>Playing</label>
                    </span>
                    <span className='space-x-1'>
                        <input className="form-check-input border" type="checkbox" name="hobbies" onChange={handleChange} value="Others" />
                        <label>Others</label>
                    </span>
                </span>

                <br></br><br></br>

                <button  className='rounded-xl border px-5 py-1 bg-transparent hover:bg-sky-400  hover:text-white' onClick={e => {
                    e.preventDefault();
                    setEmps([
                        ...emps,
                        { Id: employee.Id, Name: employee.Name, Address: employee.Address, Gender: employee.Gender, DOJ: employee.DOJ, hobbies: hobbies.hobby }
                    ])
                }}>save</button>
            </fieldset><br></br><br></br>
            <div className='mb-3 flex justify-between'>
                <span className='space-x-2'>
                    <label>By Month :  </label>
                    <input className="form-control border " type="number" onChange={e => setFmonth(e.target.value)} />
                </span>
                <span className='space-x-2 '>
                    <label>By Name :  </label>
                    <input className="form-control border " type="text" onChange={e => setFName(e.target.value)} />
                </span>
            </div>

            <table className="border-collapse border text-center  table-auto border-zinc-900 w-full ">
                <tr className="bg-neutral-400">
                    <th className="border border-zinc-900 p-2">ID</th>
                    <th className="border border-zinc-900 p-2">Name</th>
                    <th className="border border-zinc-900 p-2">Address</th>
                    <th className="border border-zinc-900 p-2">Gender</th>
                    <th className="border border-zinc-900 p-2">DOJ</th>
                    <th className="border border-zinc-900 p-2">Hobbies</th>
                </tr>
                <tbody>
                    <Display emps={emps} month={Fmonth} Name={FName}></Display>
                </tbody>
            </table>

        </div>
    )
}
