// Angular_React_Vue/Day4/Assignments/Assignment2/Source/Employee/src/app/employee/employee.component.ts
import { Component, OnInit } from '@angular/core';
import {Employee,Hobbies} from './EmployeeIterface'
@Component({
  selector: 'app-employee',
  templateUrl: './employee.component.html',
  styleUrls: ['./employee.component.css']
})

 
export class EmployeeComponent implements OnInit {
  eid: string = '';
  EName: string = '';
  Address: string = '';
  Gender: string = '';
  DOJ: string = '';
  Emps: Employee[] = [];

  FMonth: string = '';
  Fname: string = '';
  filteredbyMongth: Employee[] = [];
  filterbyname:Employee[] = [];
  hobbies:Hobbies[]= [{
      name:'Swmming',
      checked: false
    },
    {
      name:'Reading',
      checked: false
    },
    {
      name:'Travelling',
      checked: false
    },
    {
      name:'Playing',
      checked: false
    },
    {
      name:'Other',
      checked: false
    },
  ];
  selected :string[] = [];
  constructor() { }
  SaveEmp() {
    this.selected=[];
    this.hobbies.filter((value) => {
      if(value.checked === true){
        this.selected.push(value.name)
      }
      return value;
    });
    this.Emps.push({ ID: this.eid, Name: this.EName, Address: this.Address, Gender: this.Gender, DOJ: this.DOJ, Hobbies: this.selected.join(',') });
  }
  getBymonth() {
    this.filteredbyMongth = this.Emps.filter(value => value.DOJ.split('-')[1] == this.FMonth)
  }
  getByName() {
    this.filterbyname = this.Emps.filter(value => value.Name == this.Fname);
  }
  ngOnInit(): void {
  }
}

<div class="m-5">
    <fieldset action="" class="border p-5 ">
        <legend>Employee</legend>
        <label for="eid">Employee ID : </label>
        <input type="number" class="from-control border" name="EmpID" id="eid" [(ngModel)]="eid"><br><br>
        <label for="name">Eployee's Name : </label>
        <input type="text" class="from-control border" name="EName" id="name" [(ngModel)]=EName><br><br>
        <label for="Address">Address : </label>
        <input type="text" class="from-control border" name="Address" id="Address" [(ngModel)]=Address><br><br>
        <label for="Gender">Select Gender : </label>
        <span class="space-x-4">
            <span class="space-x-1">
                <input type="radio" name="gender" id="male" [(ngModel)]=Gender value="Male"><label
                    for="male">Male</label>
            </span>
            <span class="space-x-1">

                <input type="radio" name="gender" id="female" [(ngModel)]=Gender value="Female"><label
                    for="female">Female</label>
            </span>
        </span>
        <br><br>
        <label for="DOJ">DOJ : </label>
        <input type="date" name="DOJ" id="DOJ" [(ngModel)]="DOJ"><br><br>
        <label for="hobbies">Hobbies : </label>
        <span class="space-x-4">
            <span class="space-x-1" *ngFor="let d of hobbies">
                <input type="checkbox" [checked]="d.checked" (change)="d.checked = !d.checked"><label>{{d.name}}</label>
            </span>
        </span>
        <br><br>
        <button class="border rounded-xl hover:text-white hover:bg-blue-400" (click)="SaveEmp()">save</button>
    </fieldset><br><br><br>

    <div>
        <label for="MonthFilter">By Month : </label>
        <input type="number" name="MonthFilter" id="MonthFilter" [(ngModel)]="FMonth" (keyup)="getBymonth()">
        <label for="SortByName">By Name : </label>
        <input type="text" name="SortByName" id="SortByName" [(ngModel)]="Fname" (keyup)="getByName()">
    </div><br>

    <table class="border-collapse border text-center  table-auto border-zinc-900 w-full">
        <caption>Employees Detail : </caption>
        <tr class="bg-neutral-400">
            <th class="border border-zinc-900 p-2">ID</th>
            <th class="border border-zinc-900 p-2">Name</th>
            <th class="border border-zinc-900 p-2">Address</th>
            <th class="border border-zinc-900 p-2">Gender</th>
            <th class="border border-zinc-900 p-2">DOJ</th>
            <th class="border border-zinc-900 p-2">Hobbies</th>
        </tr>
        <tr *ngIf="Emps.length === 0 ">
            <td colspan="6" class="text-3xl"> There is no data </td>
        </tr>
        <ng-container *ngIf="filterbyname.length !== 0 ; else secFinal">
            <tr  class="odd:bg-neutral-400" *ngFor="let i of filterbyname">
                <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
            </tr>
        </ng-container>
        <ng-template #secFinal>
            <ng-container *ngIf="filteredbyMongth.length !== 0 ; else finalblock">
                <tr class="odd:bg-neutral-400" *ngFor=" let i of filteredbyMongth">
                    <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
                </tr>
            </ng-container>
            <ng-template #finalblock>
                <tr class="odd:bg-neutral-400" *ngFor="let i of Emps">
                    <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                    <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
                </tr>
            </ng-template>
        </ng-template>
    </table>
</div>

// Angular_React_Vue/Day4/Assignments/Assignment1/Source/EmployeeDetails/src/components/Employee.vue
<script>
import '../style.css'
export default {
    data() {
        return {
            eid: '',
            EName: '',
            Address: '',
            Gender: '',
            DOJ: '',
            Emps: [],
            hobbies: [],
            FMonth: '',
            Fname: '',
            filteredbyMongth: [],
            filterbyname: []
        }
    },
    methods: {
        SaveEmp() {
            this.Emps.push({ ID: this.eid, Name: this.EName, Address: this.Address, Gender: this.Gender, DOJ: this.DOJ, Hobbies: this.hobbies.join(',') });
        },
        getBymonth() {
            this.filteredbyMongth = this.Emps.filter(value => value.DOJ.split('-')[1] == this.FMonth)
        },
        getByName() {
            this.filterbyname = this.Emps.filter(value => value.Name.match(this.Fname));
        }
    }
}
</script>

<template>
    <div class="mx-5">
        <fieldset action="" class="border p-5">
            <legend>Employee</legend>
            <label for="eid">Employee ID : </label>
            <input type="number" class="border form-control" name="EmpID" id="eid" v-model=eid><br><br>
            <label for="name">Eployee's Name : </label>
            <input type="text" class="border form-control" name="EName" id="name" v-model=EName><br><br>
            <label for="Address">Address : </label>
            <input type="text" class="border form-control" name="Address" id="Address" v-model=Address><br><br>
            <label for="Gender">Select Gender : </label>
            <span class="space-x-4">
                <span class="space-x-1">
                    <input type="radio" class="form-check-input" name="gender" id="male" v-model=Gender
                        value="Male"><label for="male">Male</label>
                </span>
                <span class="space-x-1">
                    <input type="radio" class="form-check-input" name="gender" id="female" v-model=Gender
                        value="Female"><label for="female">Female</label>
                </span>
            </span>
            <br><br>
            <label for="DOJ">DOJ : </label>
            <input type="date" class="border form-control" name="DOJ" id="DOJ" v-model="DOJ"><br><br>
            <label for="hobbies">Hobbies : </label>
            <span class="space-x-4">
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Swimming" v-model="hobbies">
                    <label>Swimming</label>
                </span>
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Reading" v-model="hobbies">
                    <label>Reading</label>
                </span>
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Playing" v-model="hobbies">
                    <label>Playing</label>
                </span>
                <span class="space-x-1">

                    <input type="checkbox" class="form-check-input" name="hobbies" value="Others" v-model="hobbies">
                    <label>Others</label>
                </span>
            </span>
            <br><br>
            <button class="border rounded-xl px-5 py-1 hover:bg-blue-400 hover:text-white"
                @click.stop.prevent="SaveEmp()">save</button>
        </fieldset><br><br><br>

        <div class='mb-3 flex justify-between'>
            <span class="space-x-2">
                <label for="MonthFilter">By Month : </label>
                <input type="number" class="border form-control" name="MonthFilter" id="MonthFilter" v-model="FMonth"
                    @keyup="getBymonth">
            </span>
            <span class="space-x-2">
                <label for="SortByName">By Name : </label>
                <input type="text" class="border form-control" name="SortByName" id="SortByName" v-model="Fname"
                    @keyup="getByName">
            </span>

        </div><br>

        <table class="border-collapse border text-center  table-auto border-zinc-900 w-full ">
            <caption>Employees Detail :</caption>
            <tr class="bg-neutral-400">
                <th class="border border-zinc-900 p-2">ID</th>
                <th class="border border-zinc-900 p-2">Name</th>
                <th class="border border-zinc-900 p-2">Address</th>
                <th class="border border-zinc-900 p-2">Gender</th>
                <th class="border border-zinc-900 p-2">DOJ</th>
                <th class="border border-zinc-900 p-2">Hobbies</th>
            </tr>
            <tr v-if="Emps.length === 0">
                <td class="border text-3xl" colspan="6"> There is no data </td>
            </tr>
            <tr class="odd:bg-neutral-400" v-else-if="filteredbyMongth.length !== 0" v-for="i of filteredbyMongth">
                <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
            </tr>
            <tr class="odd:bg-neutral-400" v-else-if="filterbyname.length !== 0" v-for="i of filterbyname">
                <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
            </tr>
            <tr class="odd:bg-neutral-400" v-else v-for=" i of Emps">
                <td class="border border-zinc-900 p-1">{{ i.ID }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Name }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Address }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Gender }}</td>
                <td class="border border-zinc-900 p-1">{{ i.DOJ }}</td>
                <td class="border border-zinc-900 p-1">{{ i.Hobbies }}</td>
            </tr>
        </table>
    </div>
</template>
